server:
  port: 8080

spring:
  application:
    name: auth-api
  jpa:
    hibernate:
      ddl-auto: create # for testing purposes, should be removed!
  security:
    token:
      jwt:
        secret: ${JWT_SECRET}
        expiration: 360000
      service:
        secret: ${INTERNAL_TOKEN}
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}