server:
  port: 8080

spring:
  application:
    name: auth-api
  jpa:
    hibernate:
      ddl-auto: create # for testing purposes, should be removed!
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 360000
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

client:
  service:
    url: http://data-api:8081/api/transform
    secret: ${INTERNAL_TOKEN}